### ISSUE TITLE
Initial API

### ISSUE THREAD

**Issue by pwalsh** [opentrials/api#4]
# Description

The OpenTrials API server will expose a REST API compatible with the [OpenAPI Specification](https://openapis.org/specification).

The API server will be implemented in Node.js, using Express or hapi: there is a range of quality tooling around OpenAPIs (Swagger) for Node.js.

A high-level view of the database schema can be [found here](https://github.com/opentrials/api/issues/3). This first iteration of the API can mock out this underlying data structure until it is ready for use.

# Tasks

* [x] Setup basic server and bootstrap the swagger components
  * Our preference is to write ES6. Here is an [example app written in ES6 and transpiled on load](https://github.com/okfn/spend-publishing-dashboard/blob/master/server.js#L3)
* [x] Flesh out the basic endpoints to `GET` data based on our schema
  * [x] JSON only API
  * [x] Express relations as hyperlinks to (other) API endpoints. I'm not sure what tooling is available out of the box for this in Swagger, but Django REST Framework has a great, simple implementation of this ([Example](http://cosmopolitan.openspending.org/v1/cities/), [Docs](http://www.django-rest-framework.org/api-guide/serializers/#hyperlinkedmodelserializer))
  * **note**: There are likely many decisions to make about nesting objects vs. links to other endpoints, and so on. Let's not optimize around this too early, and rather, wait until we start building out the first app on the API, to establish some basic use patterns
* [x] Mock out the schema with a query builder, ORM etc. We'd previously used [Sequelize](http://docs.sequelizejs.com/en/latest/) at OKI, but if starting again I would have chosen [knex](https://www.npmjs.com/package/knex) and [Bookshelf](http://bookshelfjs.org)
* [x] Unit tests for core components, functional tests for API endpoints

**Comment by pwalsh** [comment]
DONE
